"""Initial schema with CompanyCache table

Revision ID: da1896c2f58d
Revises: 
Create Date: 2025-10-29 23:13:57.790723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1896c2f58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_cache',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'field_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_cache')
    # ### end Alembic commands ###